# Generated by Django 3.2.18 on 2023-04-26 01:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
